- name: Linux Groups and Users
  hosts: all
  become: yes
  tasks:
  - name: Ensure group "developers" exists
    ansible.builtin.group:
      name: developers
      state: present

  - name: Add users
    ansible.builtin.user:
      name: "{{ item }}"
      shell: /bin/bash
      group: developers
      state: present
    loop:
      - dev1
      - dev2
      - dev3
      - dev4
      - dev5
      - dev6
      - dev7
      - dev8
      - dev9
      - dev10