- name: Linux Groups and Users
  hosts: all
  become: yes
  tasks:

  - name: Remove users
    ansible.builtin.user:
      name: "{{ item }}"
      shell: /bin/bash
      group: developers
      remove: yes
      state: absent
    loop:
      - dev1
      - dev2
      - dev3
      - dev4
      - dev5
      - dev6
      - dev7
      - dev8
      - dev9
      - dev10

  - name: Ensure group "developers" absent
    ansible.builtin.group:
      name: developers
      state: absent

