- name: Linux Groups and Users
  hosts: all
  become: yes
  tasks:
  - name: Ensure group "developers" exists
    ansible.builtin.group:
      name: developers
      state: present

  - name: Create a user 'johnd' with a home directory
    ansible.builtin.user:
      name: johnd
      create_home: yes
      group: developers
      shell: /bin/bash
      state: present

  - name: Ensure user 'johnd' is in group 'developers'
    ansible.builtin.user:
      name: johnd
      groups: developers
      append: yes